# Utilise l'image Node.js
FROM node:14

# Crée un répertoire de travail à l'intérieur du conteneur
WORKDIR /usr/src/app

# Copie les fichiers package.json et package-lock.json
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie le reste de l'application dans le conteneur
COPY . .

# Expose le port sur lequel l'application va tourner
EXPOSE 9090

# Commande pour démarrer l'application
CMD ["npm", "start"]
